MODEL:
  NAME: "resnet50_ibn_a"
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: 'weights/r50_ibn_a.pth'
  # PRETRAIN_PATH: 'weights/resnet50_ibn_a_model_60.pth'
  
  # METRIC_LOSS_TYPE: 'triplet_center'
  METRIC_LOSS_TYPE: 'circle_center'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'

INPUT:
  SIZE_TRAIN: [125, 250]
  SIZE_TEST: [125, 250]
  PROB: 0 # random horizontal flip
  RE_PROB: 0 # random erasing
  PADDING: 10

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 6
  NUM_WORKERS: 2

DATASETS:
  NAMES: 'sig'
  ROOT_DIR: './dataset'
  LABEL: './label_signature.txt'
  FORGERY_CLS: False


SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.00035

  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 16

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 20
  EVAL_PERIOD: 10

TEST:
  IMS_PER_BATCH: 12
  RE_RANKING: 'no'
  WEIGHT: "path"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "log/log_25032021_circle"


